# Generated by Django 4.1 on 2023-11-07 18:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='onboard.questionresponse'),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='date_responded',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
