BEGIN;
--
-- Create model Question
--
CREATE TABLE "question" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "text" text NOT NULL, "name" varchar(255) NOT NULL, "type" varchar(20) NOT NULL, "required" boolean NOT NULL, "description" text NULL);
--
-- Create model QuestionResponse
--
CREATE TABLE "question_response" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "full_name" varchar(255) NOT NULL, "email_address" varchar(254) NOT NULL, "description" text NOT NULL, "gender" varchar(20) NOT NULL, "programming_stack" varchar(255) NOT NULL, "date_responded" timestamp with time zone NOT NULL);
--
-- Create model Option
--
CREATE TABLE "option" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "category" varchar(20) NOT NULL, "value" varchar(20) NOT NULL, "text" varchar(255) NOT NULL, "multiple" boolean NOT NULL, "question_id" bigint NOT NULL);
--
-- Create model FileProperty
--
CREATE TABLE "file_property" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "format" varchar(10) NOT NULL, "max_file_size" varchar(10) NOT NULL, "max_file_size_unit" varchar(2) NOT NULL, "multiple" boolean NOT NULL, "question_id" bigint NOT NULL);
--
-- Create model Certificate
--
CREATE TABLE "certificates" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(255) NOT NULL, "certificate" varchar(100) NOT NULL, "user_id" bigint NOT NULL);
ALTER TABLE "option" ADD CONSTRAINT "option_question_id_cd7adb60_fk_question_id" FOREIGN KEY ("question_id") REFERENCES "question" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "option_question_id_cd7adb60" ON "option" ("question_id");
ALTER TABLE "file_property" ADD CONSTRAINT "file_property_question_id_63232223_fk_question_id" FOREIGN KEY ("question_id") REFERENCES "question" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "file_property_question_id_63232223" ON "file_property" ("question_id");
ALTER TABLE "certificates" ADD CONSTRAINT "certificates_user_id_61393316_fk_question_response_id" FOREIGN KEY ("user_id") REFERENCES "question_response" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "certificates_user_id_61393316" ON "certificates" ("user_id");
COMMIT;
